# Generated by Django 5.0.2 on 2024-03-05 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordbin', '0002_profile_delete_react'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(help_text='MusicBrainz ID', max_length=36, unique=True)),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(help_text='MusicBrainz ID', max_length=36, unique=True)),
                ('album_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordbin.artist')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_artists',
            field=models.ManyToManyField(related_name='saved_by', to='recordbin.artist'),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(help_text='MusicBrainz ID', max_length=36, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='recordbin.album')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_releases',
            field=models.ManyToManyField(related_name='saved_by', to='recordbin.release'),
        ),
    ]
